### ISSUE TITLE
Error comparing to identical complex numbers

### ISSUE THREAD

**Issue by josecelano** [MarkBaker/PHPComplex#11]
Hi,

I'm using this package and I'm getting a strange behaviour using PHPUnit. It seems that comparing two complex numbers with no imaginary part fails. This is the test case to reproduce the error:

```php
<?php

use Complex\Complex;

class ComplexNumberShould extends BaseTestClass {
    /** @test */
    public function should_be_equal_if_they_have_the_same_real_and_imaginary_parts() {
        $c1 = new Complex(-2, 1);
        $c2 = new Complex(-2, 1);

        $this->assertEquals($c1, $c2);
    }

    /** @test */
    public function should_be_equal_if_they_have_the_same_real_and_imaginary_parts_but_is_not_true_for_imaginary_part_equals_0() {
        $c1 = new Complex(-2, 0, '');
        $c2 = new Complex(-2, 0, 'i');

        $this->assertNotEquals($c1, $c2);
    }

    /** @test */
    public function should_be_equal_if_they_have_the_same_real_and_imaginary_parts_with_imaginary_part() {
        $c1 = new Complex(-2, 1);
        $c2 = new Complex(-2, 1);

        $this->assertEquals($c1, $c2);
    }
}
```

The problem is one of the complex numbers does not have the `suffix`. I do not know yet why that is happening. I supposed PHPUnit object comparison does not work because one attribute is different.

I could implement an `assertEqualsComplex` but I'm comparing two `Complex` arrays.

What I do not understand is why one Complex does not have the suffix as `i` seems to be the default value. I'm forcing it in the test, but my production code do not force it. I'm creating the complex with:

```
new Complex($realPart, $imaginaryPart)
```

On the other hand, could be a good idea to add a `compare` method in order to check if two complex number are equal? In the same way we compare floats?:

https://stackoverflow.com/questions/3148937/compare-floats-in-php

**Comment by MarkBaker** [comment]
Hopefully the latest tagged release resolves this comparison problem

**Comment by josecelano** [comment]
Thank you! Fixed!
