### ISSUE TITLE
error: syntax error, unexpected '.',  in function definition 

### ISSUE THREAD

**Issue by asadkamran** [MarkBaker/PHPComplex#12]
I found this issue here while implementing PhpOffice.

>  "Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /var/www/html/example.com/public_html/includes/vendor/markbaker/complex/classes/src/operations/subtract.php on line 18"

Every function definition has extra 3  extra dots before parameter like

> function subtract(...$matrixValues){

this happen in all files and function definition.

**Also this issue in markbaker/matrix**

**Comment by MarkBaker** [comment]
And what version of PHP are you running? Those three extra dots are the array packing/unpacking operator, introduced in PHP 5.6, which is the minimum version reguirement for the library. PHPMatrix also has the same minimum version requirement

**Comment by asadkamran** [comment]
Sorry for this i new some new operators in php 7 but never know about ... dots, on this server its php 5.4. so i am looking for old version of software that can run in current configurations.
