### ISSUE TITLE
Not include all the files while library is not used

### ISSUE THREAD

**Issue by IndianaHorrscht** [MarkBaker/PHPComplex#14]
It seems that all the files abs.php, acos.php etc. are included as soon as the composer autoloader gets initialized, even when I'm not using the complex library. (The same goes for markbaker/matrix.) Is there a way to avoid this? It doesn't do any harm but it seems unneccessary and is using resources.

**Comment by MarkBaker** [comment]
Until PHP itself supports autoloading of userland functions, this isn't possible. These function stubs are what allow the methods to be called procedurally: (e.g.)
```php
$complexString = '1.23-4.56i';

echo Complex\sinh($complexString);
``` 
for those developers that prefer a procedural approach.

The code in these stub functions is deliberately kept as small as possible, with all the real work being handled inside the classes that are autoloaded only when required.

**Comment by IndianaHorrscht** [comment]
I see, thank you for the explanation.
