### ISSUE TITLE
Unexpected '.' variable in add.php

### ISSUE THREAD

**Issue by FoxyBit** [MarkBaker/PHPComplex#5]
I have been trying to use this library, but I am coming up with the following error:

syntax error, unexpected '.', expecting '&amp;' or variable (T_VARIABLE) in vendor/markbaker/complex/classes/src/operations/add.php on line 18

I have tried looking online and can't find any other solution to it.

My PHP version is 5.4.45. 

Any other information required, please ask.

**Comment by MarkBaker** [comment]
Unfortunately, the PHPComplex library has a minimum PHP version requirement of 5.6.0, using features of PHP - in this case, PHP's "splat" operator - that didn't exist prior to 5.6.

This is identified in the composer.json file, and should have been highlighted if you used composer require to install the library
```
"require": {
    "php": "^5.6.0|^7.0.0"
},
```
though I should probably also add a comment indicating this minimum version to the readme file as well

**Comment by FoxyBit** [comment]
I am using PHP version 7.1, so should this not work?

**Comment by MarkBaker** [comment]
Sorry? Your original issue post said that `My PHP version is 5.4.45.`
PHPComplex should work without issue against PHP 7.1: which version of PHP are you actually running? Are you running the same version on the command line and for your web interface?

**Comment by FoxyBit** [comment]
My apologies. I forgot that I put that version in without explaining. I have upgraded the server to use version 7.1.

I have checked the command line and that is still the version 5.4.45 whereas the version on the web interface is 7.1. That seems to be the issue of why it's not working. I'll get that sorted and it will probably work after that.

Thanks for the help, I wouldn't have thought to look there otherwise.

**Comment by homerhappiness** [comment]
Hi, is there any other way to use splat having 5.5.38 version of php? or do I need to upgrade the version of my php? 

Thanks

**Comment by MarkBaker** [comment]
This library is intended for use with versions of PHP that are actively supported, and (as such) uses features that are available in those versions of PHP. That splat operator which was introduced in PHP 5.6, which is itself EOL on 31st December 2018. PHP version 5.5 was EOL on 21st June 2016, 2½ years ago, and you should be upgrading anyway, not simply for the sake of this library, but to ensure that you are using a version of PHP that is actively supported and receives regular security updates.

**Comment by BrianTolman** [comment]
I am having this same issue, but we are running php 7.1.  Any suggestions?

**Comment by MarkBaker** [comment]
If you're running PHP 7.1, then you should have the splat operator; if you're getting the same error, then double-check your PHP version

**Comment by BrianTolman** [comment]
Say Hello to the Dreamhost support people, who can view this thread, and they are assuring me that we are running 7.1

**Comment by BrianTolman** [comment]
We've tested using 5.6FastCGI, 7.1FastCGI and 7.2FastCGI - same error the whole time.

PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /home/**/***.org/wp-content/plugins/verified-download-HdktgC/lib/markbaker/complex/classes/src/operations/add.php on line 18
Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /home/**/***.org/wp-content/plugins/verified-download-HdktgC/lib/markbaker/complex/classes/src/operations/add.php on line 18

**Comment by MarkBaker** [comment]
Then I apologise that somehow PHP is failing to work, because I haven't a clue how I can debug an issue at the core php level.... Variadics (aka the splat operator) was introduced in PHP 5.6.0 - http://php.net/manual/en/migration56.new-features.php#migration56.new-features.variadics
All tests run cleanly on Travis against PHP 5.6.37, 7.0.25, 7.1.11, 7.2.10, 7.3.0RC3 and the nightly build 7.4.0-dev - https://travis-ci.org/MarkBaker/PHPComplex/builds/441140760 -

**Comment by Ocramius** [comment]
@BrianTolman please try uploading this file to your host, then try running it via your same production environment:

```php
<?php

(function (string ...$args) {
    echo implode(' ', $args);
})('Hello', 'world!');
```

**Comment by arievanden** [comment]
If you're getting this error in a CRON job under Webmin, run "php -v" as a job and see what the output is. In the case of running in Webmin env, you can have different versions of php, so check this. Mine was running with the older version, not php v7.x.

If it says "php 5.4" as the output, find the path for the updated version, such as "/opt/rh/rh-php72/root/usr/bin/php", and add the absolute path pointing to php to the cron job. 

Ex. cron command: "/opt/rh/rh-php72/root/usr/bin/php /path_to_your_script/script.php"
