### ISSUE TITLE
PHP5.6 is not compatible with Coercive mode

### ISSUE THREAD

**Issue by blueberry-media** [MarkBaker/PHPComplex#7]
Not working in PHP5.6 (http://php.net/manual/en/migration70.new-features.php)

add.php has `function add(...$complexValues)` this is not working in php 5.6
https://github.com/MarkBaker/PHPComplex/blob/1ea674a8308baf547cbcbd30c5fcd6d301b7c000/classes/src/operations/add.php#L18

**Comment by MarkBaker** [comment]
There is no "coercive" type hinting here. `function add(...$complexValues)` is simply using the "splat" operator (aka avariadics), [introduced in PHP 5.6](http://php.net/manual/en/migration56.new-features.php#migration56.new-features.variadics)
